const photoSources = {
  "nago-masculina": "Artistic Braiding by Yessenia.jpg",
  "nago-tiara": "Cornrow style (Unsplash).jpg",
  "nago-lateral": "Cornrows Into Braided Bun.JPG",
  "nago-topo": "Orit's Cornrows work.jpg",
  "boxeadora-com-cachos": "Cornrows by David Shankbone.jpg",
  "boxeadora-cachos-na-ponta": "Braid-wil7148.jpg",
  "boxeadora-alimentada": "Cornrows.jpg",
  "boxeadora-simples": "Mybraids.jpg",
  "ghana-com-cachos": "Fine Braids, Dimma (13307706094).jpg",
  "ghana-cachos-na-ponta": "Hair Design, Tigray (9800999074).jpg",
  "ghana-sem-cachos": "Natural twisted hair.jpg",
  "ghana-mais-10-com-cachos": "Long cornrows.jpg",
  "box-braids-chanel": "Box Braids.jpg",
  "box-braids-m-comprida": "A braid display.jpg",
  "box-braids-nago-lateral": "African girl braids.jpg",
  "box-braids-g-comprida": "A braid display 02.jpg",
  "gypsy-m-com-cachos": "A lady on braids.jpg",
  "gypsy-g-com-cachos": "Hair.jpg",
  "gypsy-boho": "Halima Bah 2.jpg",
  "gypsy-g-sem-cacho": "Mrs emmyon and baby emmyon.jpg",
  "goddess-m-com-cachos": "African damsel.jpg",
  "goddess-g-com-cachos": "African Village at Arts Centre.jpg",
  "goddess-boho": "Omo River Valley IMG 0980.jpg",
  "fulani-m-sem-cacho": "Fulani Woman from Niger.jpg",
  "fulani-p-sem-cacho": "Senegalese braids.jpg",
  "fulani-freestyle-com-cacho": "FulaniWoman2.jpg",
  "fulani-cabelo-organico": "Mali Peul girl.jpg",
  "french-curl-p": "Arianna Polius.jpg",
  "french-curl-pp": "DianeSolo.jpg",
  "french-curl-curta": "Kdfmeche01.JPG",
  "french-curl-fulani": "Kdfmeche02.JPG",
  "faux-locs-comprida": "Freeform Dreadlocks.jpg",
  "faux-locs-com-cachos": "Dreadlocks of an African-American person, after being unwound from Bantu knots.jpg",
  "twist-masculina": "Berkant Usen With Cornrows.jpg",
  "twist-freestyle": "Beautiful african girls braided hair.jpg",
  "twist-tradicional": "Braiding of hair.jpg",
  "twist-cabelo-organico": "Woman with purple hair and lipstick.jpg"
};

const commonsImageUrl = (fileName) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(fileName)}?width=900`;
const commonsSourceUrl = (fileName) => `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(fileName)}`;
